import { jsPDF } from 'jspdf';
import flattenTree from './treeFlattener';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000';

/**
 * Generates a beautiful 3-page PDF analysis report matching the website theme.
 * Downloads the file on the user's system.
 * 
 * @param {string} repoName - The repository name
 * @param {object} repoData - The complete parsed repository data
 * @param {string} selectedBranch - The currently selected branch
 * @param {string} username - The owner's username
 */
export async function generatePdfReport(repoName, repoData, selectedBranch, username) {
  // 1. Fetch AI Repository Summary from Database/API (Fallback to synthesized metadata summary if unavailable)
  let aiSummary = '';
  try {
    const branchQuery = selectedBranch ? `?branch=${encodeURIComponent(selectedBranch)}` : '';
    const latestResponse = await fetch(`${API_BASE_URL}/summaries/latest/${username}/${repoName}${branchQuery}`);

    if (latestResponse.ok) {
      const latestRun = await latestResponse.json();
      if (latestRun?.id) {
        const runResponse = await fetch(`${API_BASE_URL}/summaries/run/${latestRun.id}`);
        if (runResponse.ok) {
          const runData = await runResponse.json();
          aiSummary = runData?.repoSummary?.summary || '';
        }
      }
    }
  } catch (err) {
    console.warn("Failed to fetch repository summary from API, using fallback synthesis.", err);
  }

  // Build high-fidelity fallback summary if empty
  if (!aiSummary || aiSummary.trim() === '') {
    const readmeExcerpt = repoData?.metadata?.readmeExcerpt
      ? repoData.metadata.readmeExcerpt.substring(0, 450) + '...'
      : 'No README description was found in this repository.';

    aiSummary = `This is a comprehensive code intelligence report for the repository ${username}/${repoName}. Our static analysis engine has thoroughly parsed the source files, cataloged functions and imports, mapped trace paths, and resolved API endpoints.

Ecosystem Insights:
- Primary Frameworks: ${repoData?.metadata?.frameworks?.join(', ') || 'Vanilla JS / Web Ecosystem'}
- Detected Architecture: Clean component modularization with structured route endpoints and services.

Readme Insights:
${readmeExcerpt}`;
  }

  // 2. Initialize jsPDF (A4 dimensions: 210mm x 297mm)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  let totalPages = 3;
  const bgColor = '#0f172a'; // Deep professional dark background (Slate-900)
  const primaryColor = '#c084fc'; // Violet / Lilac accent (accent-primary)
  const secondaryColor = '#3b82f6'; // Sky Blue accent (accent-secondary)
  const textDark = '#f8fafc'; // Slate-50 (text-primary)
  const textSecondary = '#cbd5e1'; // Slate-300 (text-secondary)
  const textMuted = '#94a3b8'; // Slate-400 (text-muted)
  const borderLight = '#2e3748'; // Slate-700 / Translucent white borders
  const cardBg = '#162032'; // Premium Slate-800 translucent-style card background

  // 3. Helper Functions for Layout & Decoration
  const drawPageBackground = () => {
    doc.setFillColor(bgColor);
    doc.rect(0, 0, 210, 297, 'F');
  };

  const drawPageBorder = (pageNum) => {
    // Beautiful top double-colored accent border
    doc.setFillColor(primaryColor);
    doc.rect(15, 8, 90, 2, 'F');
    doc.setFillColor(secondaryColor);
    doc.rect(105, 8, 90, 2, 'F');
  };

  const drawHeader = (titleText) => {
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(primaryColor);
    doc.text('CODESPHERE 2.0 // INTELLIGENCE REPORT', 15, 17);

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(textMuted);
    doc.text(`Branch: ${selectedBranch || 'main'}`, 195, 17, { align: 'right' });

    // Thin grey header line
    doc.setDrawColor(borderLight);
    doc.setLineWidth(0.3);
    doc.line(15, 20, 195, 20);
  };

  const drawFooter = (pageNum) => {
    doc.setDrawColor(borderLight);
    doc.setLineWidth(0.3);
    doc.line(15, 280, 195, 280);

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(textMuted);
    doc.text('Generated by CodeSphere 2.0 Static Analysis Engine', 15, 286);
    doc.text(`Page ${pageNum} of ${totalPages}`, 195, 286, { align: 'right' });
  };

  // Flatten tree for stats if needed
  const { totalFiles, languages } = flattenTree(repoData?.tree);

  // Helper to add a new page with background, borders, and standard headers
  const addNewPage = () => {
    doc.addPage();
    drawPageBackground();
    drawPageBorder(doc.internal.getNumberOfPages());
    drawHeader();
  };

  // ==========================================
  // PAGE 1: Executive Repository Summary
  // ==========================================
  drawPageBackground();
  drawPageBorder(1);
  drawHeader();

  // Repository Title Header
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(textDark);
  doc.text(repoName, 15, 32);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(textSecondary);
  doc.text(`Analysis Report for ${username}/${repoName} GitHub repository`, 15, 38);

  // Stats Grid - 4 Cards (2x2)
  const stats = [
    { label: 'TOTAL FILES', value: repoData?.metadata?.totalFiles || totalFiles || 0, color: '#3b82f6' },
    { label: 'FUNCTIONS PARSED', value: repoData?.metadata?.totalFunctions || 0, color: '#a855f7' },
    { label: 'PACKAGE IMPORTS', value: repoData?.metadata?.totalImports || 0, color: '#2dd4bf' },
    { label: 'API ROUTE ENDPOINTS', value: repoData?.metadata?.totalEndpoints || repoData?.apiEndpoints?.length || 0, color: '#10b981' }
  ];

  stats.forEach((stat, idx) => {
    const col = idx % 2;
    const row = Math.floor(idx / 2);
    const x = 15 + col * 92;
    const y = 44 + row * 22;
    const width = 88;
    const height = 18;

    // Card background
    doc.setFillColor(cardBg);
    doc.rect(x, y, width, height, 'F');

    // Accent line on left edge
    doc.setFillColor(stat.color);
    doc.rect(x, y, 3, height, 'F');

    // Card border
    doc.setDrawColor(borderLight);
    doc.setLineWidth(0.2);
    doc.rect(x, y, width, height, 'S');

    // Label
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(textSecondary);
    doc.text(stat.label, x + 8, y + 6);

    // Value
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(textDark);
    doc.text(String(stat.value), x + 8, y + 13);
  });

  // Language Composition Section
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(textDark);
  doc.text('Language Composition', 15, 94);

  // Stacked horizontal progress bar
  const barX = 15;
  const barY = 98;
  const barWidth = 180;
  const barHeight = 5;

  // Draw base progress background
  doc.setFillColor('#1e293b');
  doc.rect(barX, barY, barWidth, barHeight, 'F');

  const langColors = ['#3b82f6', '#a855f7', '#2dd4bf', '#10b981', '#f59e0b', '#ef4444', '#64748b'];
  let currentX = barX;

  // Draw stacked elements
  const activeLangs = languages?.slice(0, 6) || [];
  activeLangs.forEach((lang, index) => {
    const width = (lang.percentage / 100) * barWidth;
    if (width > 0) {
      doc.setFillColor(langColors[index % langColors.length]);
      doc.rect(currentX, barY, width, barHeight, 'F');
      currentX += width;
    }
  });

  // Language legend list
  let legendX = 15;
  let legendY = 109;
  activeLangs.forEach((lang, index) => {
    // Wrap to next line if it exceeds limit
    if (legendX > 170) {
      legendX = 15;
      legendY += 6;
    }

    // Color dot
    doc.setFillColor(langColors[index % langColors.length]);
    doc.circle(legendX + 1.5, legendY - 1, 1.2, 'F');

    // Label & Percentage
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(textDark);
    doc.text(`${lang.name}:`, legendX + 4, legendY);

    doc.setFont('Helvetica', 'normal');
    doc.setTextColor(textSecondary);
    doc.text(`${lang.percentage}%`, legendX + doc.getTextWidth(`${lang.name}:`) + 5, legendY);

    legendX += doc.getTextWidth(`${lang.name}: ${lang.percentage}%`) + 12;
  });

  // Executive AI Summary Section
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(textDark);
  doc.text('Executive AI Code Summary', 15, 126);

  // Summary box
  const boxY = 130;
  const boxHeight = 140;
  doc.setFillColor(cardBg);
  doc.rect(15, boxY, 180, boxHeight, 'F');

  doc.setDrawColor(primaryColor);
  doc.setLineWidth(0.8);
  doc.line(15, boxY, 15, boxY + boxHeight); // Lilac left accent bar

  doc.setDrawColor(borderLight);
  doc.setLineWidth(0.2);
  doc.rect(15, boxY, 180, boxHeight, 'S');

  // Text inside summary box
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9.2);
  doc.setTextColor(textSecondary);

  const wrappedLines = doc.splitTextToSize(aiSummary, 168);
  let textY = boxY + 8;

  // Make sure text doesn't overflow the box container on page 1
  const maxLinesOnPage1 = 29;
  const linesToRender = wrappedLines.slice(0, maxLinesOnPage1);
  linesToRender.forEach(line => {
    doc.text(line, 21, textY);
    textY += 4.5;
  });

  if (wrappedLines.length > maxLinesOnPage1) {
    doc.setFont('Helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(textMuted);
    doc.text('... Summary continues on folder explorer logs ...', 21, textY + 2);
  }

  // ==========================================
  // PAGE 2+: Directory Architecture & Dependencies
  // ==========================================
  addNewPage();

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(textDark);
  doc.text('Directory Explorer & Code Architecture', 15, 30);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(textSecondary);
  doc.text('Nested folder structures representing the static core components of the project.', 15, 35);

  // Construct printable tree nodes (NO limit on depth or node count, showing complete repository tree)
  const printTree = [];
  const buildPrintTree = (node, prefix = '', isLast = true, depth = 0) => {
    if (!node) return;

    const isFolder = node.children && node.children.length > 0;
    const connector = depth === 0 ? '' : (isLast ? '\\-- ' : '|-- ');
    const displayLabel = isFolder ? `${node.name}/` : node.name;

    printTree.push({
      text: `${prefix}${connector}${displayLabel}`,
      isFolder,
      depth
    });

    if (node.children) {
      // Sort folders first, files second
      const sortedChildren = [...node.children].sort((a, b) => {
        const aFolder = a.children && a.children.length > 0;
        const bFolder = b.children && b.children.length > 0;
        if (aFolder && !bFolder) return -1;
        if (!aFolder && bFolder) return 1;
        return a.name.localeCompare(b.name);
      });

      const nextPrefix = depth === 0 ? '' : prefix + (isLast ? '    ' : '|   ');

      sortedChildren.forEach((child, index) => {
        buildPrintTree(
          child,
          nextPrefix,
          index === sortedChildren.length - 1,
          depth + 1
        );
      });
    }
  };

  buildPrintTree(repoData?.tree);

  // Render tree lines inside beautiful dynamic glass cards
  doc.setFont('Courier', 'bold');
  doc.setFontSize(8.5);

  let treeY = 44;
  let pageStartIndex = 0;

  // Draw the initial card background for the first tree page
  const drawTreePageCard = (startIndex) => {
    // Calculate how many nodes will fit on this page (max 46 nodes per page)
    const nodesOnThisPage = Math.min(printTree.length - startIndex, 46);
    const cardHeight = nodesOnThisPage * 4.8 + 6;

    doc.setFillColor(cardBg);
    doc.rect(15, 38, 180, cardHeight, 'F');
    doc.setDrawColor(borderLight);
    doc.setLineWidth(0.2);
    doc.rect(15, 38, 180, cardHeight, 'S');

    // Draw top colored accent line on the very first tree page card
    if (startIndex === 0) {
      doc.setFillColor(secondaryColor);
      doc.rect(15, 38, 180, 1.2, 'F');
    }
  };

  // Draw first card background before printing nodes
  drawTreePageCard(pageStartIndex);

  printTree.forEach((node, index) => {
    // If the next line will exceed the printable area, wrap to the next page
    if (treeY > 260) {
      // Add a fresh page
      addNewPage();
      doc.setFont('Courier', 'bold');
      doc.setFontSize(8.5);

      // Draw card background for the new page BEFORE rendering text
      pageStartIndex = index;
      drawTreePageCard(pageStartIndex);

      // Reset y coordinate
      treeY = 44;
    }

    if (node.isFolder) {
      doc.setTextColor(primaryColor);
    } else {
      doc.setTextColor(textDark);
    }
    doc.text(node.text, 21, treeY);
    treeY += 4.8;
  });

  // Dependencies Card Section placed dynamically after the tree
  let depY = treeY + 8;
  if (depY + 65 > 270) {
    addNewPage();
    depY = 32;
  }

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(textDark);
  doc.text('Key Frameworks & Dependency Ecosystem', 15, depY);

  depY += 5; // Start card y coordinate
  const depHeight = 65;
  doc.setFillColor(cardBg);
  doc.rect(15, depY, 180, depHeight, 'F');
  doc.setDrawColor(borderLight);
  doc.rect(15, depY, 180, depHeight, 'S');

  doc.setFillColor(primaryColor);
  doc.rect(15, depY, 180, 1.2, 'F');

  // List key imports
  const keyDeps = repoData?.metadata?.frameworks || [];
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(textDark);
  doc.text('Primary Ecosystems:', 22, depY + 8);
  doc.setFont('Helvetica', 'normal');
  doc.setTextColor(textSecondary);
  doc.text(keyDeps.join(', ') || 'Vanilla Node.js / JavaScript Modules', 62, depY + 8);

  // Descriptions of folders and architectural roles
  doc.setFont('Helvetica', 'bold');
  doc.setTextColor(textDark);
  doc.text('Architectural Role mapping:', 22, depY + 16);

  const roles = [
    { path: 'backend/src/services', desc: 'AI Summaries, dependencies engines, tree-sitter core parsing' },
    { path: 'backend/src/lib', desc: 'Prisma Client, Database connections & Neon settings' },
    { path: 'frontend/src/components', desc: 'React Flow Canvas tree charts, file views, and API lists' },
    { path: 'frontend/src/pages', desc: 'Main control center, routers, and analytical dashboard' }
  ];

  roles.forEach((role, index) => {
    const roleY = depY + 24 + index * 9;

    // Bullet dot
    doc.setFillColor(secondaryColor);
    doc.circle(23, roleY - 1, 0.8, 'F');

    doc.setFont('Courier', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(primaryColor);
    doc.text(role.path, 26, roleY);

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(textSecondary);
    doc.text(`-  ${role.desc}`, 68, roleY);
  });

  // ==========================================
  // PAGE 3+: API Gateway & Endpoints Catalog
  // ==========================================
  addNewPage(); // Start the API catalog on a fresh page

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(textDark);
  doc.text('API Gateway & Server Endpoints Catalog', 15, 30);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(textSecondary);
  doc.text('Parsed REST API endpoints detected inside the server router controls.', 15, 35);

  // Table structure variables
  const colWidths = { method: 24, path: 96, handler: 60 };
  const headers = { method: 'METHOD', path: 'API ENDPOINT ROUTE', handler: 'HANDLER FILE / ORIGIN' };

  let rowY = 42;

  const drawTableHeader = (yPos) => {
    doc.setFillColor('#1e293b');
    doc.rect(15, yPos, 180, 8, 'F');

    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor('#ffffff');
    doc.text(headers.method, 17, yPos + 5.5);
    doc.text(headers.path, 15 + colWidths.method + 5, yPos + 5.5);
    doc.text(headers.handler, 15 + colWidths.method + colWidths.path + 5, yPos + 5.5);
  };

  drawTableHeader(rowY);
  rowY += 8;

  // Render ALL api endpoints dynamically wrapping pages as needed
  const endpoints = repoData?.apiEndpoints || [];

  endpoints.forEach((ep, index) => {
    // If the next row exceeds page limit, add a new page and redraw headers
    if (rowY + 11 > 270) {
      addNewPage();
      rowY = 32;
      drawTableHeader(rowY);
      rowY += 8;
    }

    // Alternating rows
    if (index % 2 === 1) {
      doc.setFillColor(cardBg);
      doc.rect(15, rowY, 180, 11, 'F');
    }

    // Border line at the bottom of row
    doc.setDrawColor(borderLight);
    doc.setLineWidth(0.2);
    doc.line(15, rowY + 11, 195, rowY + 11);

    // Method Badge background color
    const methodStr = (ep?.method || 'GET').toUpperCase();
    let badgeColor = '#64748b';
    let badgeText = '#ffffff';
    if (methodStr === 'GET') badgeColor = '#10b981';
    else if (methodStr === 'POST') badgeColor = '#a855f7';
    else if (methodStr === 'PUT') badgeColor = '#f59e0b';
    else if (methodStr === 'DELETE') badgeColor = '#ef4444';

    // Draw method badge
    doc.setFillColor(badgeColor);
    doc.rect(17, rowY + 2.5, 16, 6, 'F');

    // Method Badge Text
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(badgeText);
    doc.text(methodStr, 25, rowY + 6.8, { align: 'center' });

    // Path details
    doc.setFont('Courier', 'bold');
    doc.setFontSize(8.2);
    doc.setTextColor(textDark);
    doc.text(ep?.path || '/', 15 + colWidths.method + 5, rowY + 6.8);

    // Handler file
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(textSecondary);
    doc.text(ep?.handlerFile || 'unknown script', 15 + colWidths.method + colWidths.path + 5, rowY + 6.8);

    rowY += 11;
  });

  // Empty state if no endpoints detected
  if (endpoints.length === 0) {
    doc.setFont('Helvetica', 'italic');
    doc.setFontSize(9.5);
    doc.setTextColor(textMuted);
    doc.text('No server-side router API endpoints detected in this repository branch.', 50, rowY + 10);
    rowY += 15;
  }

  // Verification block dynamically placed after the table
  let conY = rowY + 5;
  if (conY + 25 > 270) {
    addNewPage();
    conY = 32;
  }

  doc.setDrawColor(borderLight);
  doc.setLineWidth(0.4);
  doc.line(15, conY, 195, conY);

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(textDark);
  doc.text('Static Intelligence Verification Signature', 16, conY + 6);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8.2);
  doc.setTextColor(textSecondary);
  doc.text(`This report compiled static analysis metrics across ${totalFiles} code modules at ${new Date().toLocaleDateString()}.`, 16, conY + 11);
  doc.text('The structures, dependency flows, and trace definitions are cryptographically signed by CodeSphere 2.0.', 16, conY + 15);

  // Draw logo details
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor);
  doc.text('CODESPHERE 2.0 ENGINE', 195, conY + 11, { align: 'right' });

  // ==========================================
  // POST-PROCESSING: Dynamic Footer & Page Numbers
  // ==========================================
  totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(borderLight);
    doc.setLineWidth(0.3);
    doc.line(15, 280, 195, 280);

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(textMuted);
    doc.text('Generated by CodeSphere 2.0 Static Analysis Engine', 15, 286);
    doc.text(`Page ${i} of ${totalPages}`, 195, 286, { align: 'right' });
  }

  // 5. Save and trigger PDF download on client browser
  doc.save(`${repoName}_code_intelligence_report.pdf`);
}
